//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lands.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Lands.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        public static string AlphaCode2 {
            get {
                return ResourceManager.GetString("AlphaCode2", resourceCulture);
            }
        }
        
        public static string AlphaCode3 {
            get {
                return ResourceManager.GetString("AlphaCode3", resourceCulture);
            }
        }
        
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        public static string Subregion {
            get {
                return ResourceManager.GetString("Subregion", resourceCulture);
            }
        }
        
        public static string Demonym {
            get {
                return ResourceManager.GetString("Demonym", resourceCulture);
            }
        }
        
        public static string GINI {
            get {
                return ResourceManager.GetString("GINI", resourceCulture);
            }
        }
        
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        public static string CIOC {
            get {
                return ResourceManager.GetString("CIOC", resourceCulture);
            }
        }
        
        public static string Borders {
            get {
                return ResourceManager.GetString("Borders", resourceCulture);
            }
        }
        
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        public static string Statics {
            get {
                return ResourceManager.GetString("Statics", resourceCulture);
            }
        }
        
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        public static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        public static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        public static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        public static string ConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmPlaceHolder", resourceCulture);
            }
        }
        
        public static string ConfirmValidation {
            get {
                return ResourceManager.GetString("ConfirmValidation", resourceCulture);
            }
        }
        
        public static string EmailValidation2 {
            get {
                return ResourceManager.GetString("EmailValidation2", resourceCulture);
            }
        }
        
        public static string PasswordValidation2 {
            get {
                return ResourceManager.GetString("PasswordValidation2", resourceCulture);
            }
        }
        
        public static string ConfirmValidation2 {
            get {
                return ResourceManager.GetString("ConfirmValidation2", resourceCulture);
            }
        }
        
        public static string UserRegisteredMessage {
            get {
                return ResourceManager.GetString("UserRegisteredMessage", resourceCulture);
            }
        }
        
        public static string SourceImageQuestion {
            get {
                return ResourceManager.GetString("SourceImageQuestion", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
    }
}
